# Generated by Django 5.2.12 on 2026-03-29 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user_id', models.CharField(max_length=64)),
                ('_access_token', models.TextField(db_column='access_token')),
                ('refresh_metadata', models.JSONField(blank=True, default=dict)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channels_facebookconnection',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=64)),
                ('page_name', models.CharField(max_length=512)),
                ('page_image_url', models.URLField(blank=True, max_length=1024)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('_page_access_token', models.TextField(db_column='page_access_token')),
                ('is_selected_default', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='channels.facebookconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'channels_facebookpage',
                'ordering': ['page_name'],
                'unique_together': {('connection', 'page_id')},
            },
        ),
    ]
